name: RedisAgentBuild

on:
  push:
    branches:
      - main
    paths:
      - server/server.Dockerfile
      - server/requirements.txt
      - client/package.json
      - client/client.Dockerfile
      - .github/workflows/**

env:
  DOCKER_BUILDKIT: 1

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Get the current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> ${GITHUB_ENV}

      - name: Build and Push Server
        uses: docker/build-push-action@v3
        with:
          context: server
          file: server/server.Dockerfile
          push: true
          tags: |
            ${{ secrets.SERVER_REGISTRY_IMAGE }}:main-${{ env.CURRENT_DATE }}
            ${{ secrets.SERVER_REGISTRY_IMAGE }}:main
          cache-from: |
            type=registry,ref=${{ secrets.SERVER_REGISTRY_IMAGE }}:main
          cache-to: |
            type=inline

      - name: Build and Push Client
        uses: docker/build-push-action@v3
        with:
          context: client
          file: client/client.Dockerfile
          push: true
          tags: |
            ${{ secrets.CLIENT_REGISTRY_IMAGE }}:main-${{ env.CURRENT_DATE }}
            ${{ secrets.CLIENT_REGISTRY_IMAGE }}:main
          # cache-from: |
          #   type=registry,ref=${{ secrets.CLIENT_REGISTRY_IMAGE }}:main
          # cache-to: |
          #   type=inline
